### ISSUE TITLE
4.2-paho-mqtt-colab-sdl-demo-test

### ISSUE THREAD

**Issue by ianfoster** [sparks-baird/self-driving-lab-demo#170]
I believe that line 5 in the final cell:
`true_inputs = pd.DataFrame({key: val for key, val in zip(["R", "G", "B"], sdl.get_target_inputs())}, index=[0])`
should be replaced with:
```
target_inputs = sdl.get_target_inputs()
true_inputs = pd.DataFrame({key: target_inputs[key] for key in target_inputs}, index=[0])
```
as the former evaluates to {'R' : 'R', 'G' : 'G', 'B' : 'B'}

**Comment by sgbaird** [comment]
Not sure how I missed this. This is likely due to one of the API changes. Thank you for the great catch! I verified this and will pull the change into `main` soon.
