### ISSUE TITLE
Getting error messages when running 'main.py'

### ISSUE THREAD

**Issue by shooyonekawa** [sparks-baird/self-driving-lab-demo#188]
Hi @sgbaird, 
I downloaded sdl_demo.zip version 0.8.1 and ran 'main.py' on Thonny but got the error messages shown in the attached image. It seems like importing 'Sensor' from 'as7341_sensor' and 'AS7341' 'AS7341_MODE_SPM' from 'as7341' was failed. Do you have any idea how to fix this? 
![Screenshot 2023-03-24 184218](https://user-images.githubusercontent.com/118077755/227660484-048cf54b-a5bc-40fd-be51-16ab4fc4e9b1.png)

I tried to reboot it, but line 44, sleep(5.0), causes connection lost 
![image](https://user-images.githubusercontent.com/118077755/227660627-2e4c055a-3268-46d8-b34f-ba9cde14f125.png)

**Comment by sgbaird** [comment]
Hi @shooyonekawa, thanks for your patience. I was traveling at a conference. I saw that you closed this issue. Were you able to resolve it?

If not, still happy to help troubleshoot. You may want to check that the Grove connector is connected to Grove port #6 (closest to the RGB LED). If it's a network connection issue, then the most likely issue is that the network you're connecting to isn't a 2.4 GHz WPA-2 network (e.g., phone hotspot in extended compatibility mode).
